lab7/labs_control/config/routes.rb
Rails.application.routes.draw do
  
  resources :lab_reports do
    resources :marks 
  end

  root 'lab_reports#index'
end

lab7/labs_control/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab7/labs_control/app/models/lab_report.rb
class LabReport < ApplicationRecord
    has_one :mark

    validates :title, presence: true, length: { maximum:250}
    
    validates :description, presence: true, length: { maximum:500}
end

lab7/labs_control/app/models/mark.rb
class Mark < ApplicationRecord
    belongs_to :lab_report
    
    validates :points, presence: true, inclusion: { in: 0..100 }
end

lab7/labs_control/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab7/labs_control/app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
    
    def index
      @lab_report = LabReport.all
    end

    def show
      @lab_report = LabReport.find(params[:id])
    end

    def create
      @lab_report = LabReport.new(lab_report_params)

      if (@lab_report.save)
        redirect_to @lab_report
      else
        render 'new'
      end
    end

    private def lab_report_params 
        params.require(:lab_report).permit(:title, :description)
    end

end

lab7/labs_control/app/controllers/marks_controller.rb
class MarksController < ApplicationController
    before_action :get_report

    def create 
      get_report()
      mark_letter = get_mark()
      
      @mark = @lab_report.build_mark(points: mark_letter[:mark], letter: mark_letter[:letter])
      
      if(@mark.save) 
        redirect_to '/'
      else
        render 'new'
      end 
    end
    
    def destroy
      @lab_report = LabReport.find(params[:lab_report_id])
      
      @mark = @lab_report.mark.destroy()
      
      @mark.destroy

      redirect_to '/'
    end

    private def convert_to_letter(mark)
      case mark
      when 90..100
        return 'A'
      when 80..89
        return 'B'
      when 65..79
        return 'C'
      when 55..64
        return 'D'
      when 50..54
        return 'E'
      when 1..49
        return 'F'
      else
        return 'mark is nill'
      end
    end

    private def get_mark
      hash = params.require(:mark).permit(:points)
      
      if hash[:points] != ""
        mark_int = hash[:points].to_i
        
        mark_letter = convert_to_letter(mark_int)
      
        hash = {mark: mark_int, letter: mark_letter}
      else
        mark_int = nil

        mark_letter = nil
      end

      hash = {mark: mark_int, letter: mark_letter}

      return hash
    end

    private def get_report
      @lab_report = LabReport.find(params[:lab_report_id])
    end
end

lab7/labs_control/app/helpers/application_helper.rb
module ApplicationHelper
end

lab7/labs_control/app/helpers/index_helper.rb
module IndexHelper
end

lab7/labs_control/app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

lab7/labs_control/app/helpers/marks_helper.rb
module MarksHelper
end

lab7/labs_control/app/helpers/welcome_helper.rb
module WelcomeHelper
end

lab7/labs_control/app/views/lab_reports/index.html.erb
<html>

<head>
</head>
<body>
<h1 style="text-align:center">
  Labs reports
</h1>

<div style=" padding-left: 300px; padding-right: 300px;padding-bottom: 200px;">
  <%= button_to 'Add report', new_lab_report_path,:method => :get, class: 'buttonAddReportMainPage' %>

    <% @lab_report.each do |item|%>
      <h3>
        <%= item.title%>
      </h3>
      
      <p>
        <%= item.description%>
      </p>

    <%if item.mark == nil %>
      <%= button_to 'Add mark', new_lab_report_mark_path(item.id),:method => :get, class: 'buttonAddMarkMainPage' %>  
    <%else%>
      <div class="mark">
        <%= item.mark.points %>
        <%= "("%>
        <%=item.mark.letter %>
        <%= ")"%>
      </div>
    <%end%>
<% if item.errors.any? %>
      <% item.errors.full_messages.each do |msg| %>
        <div class= "alertLabReport">
          <%= msg%>
        </div>
      <% end %>
    <% end %>
    <%if item.mark == nil%>
      <%= button_to 'remove', '/', :method => :get, data: { disable_with: 'There is nothing to remove!' }, class: 'buttonRemoveMarkFakeMainPage' %>
    <%else%>
      <%= button_to 'remove', lab_report_mark_path(item.id, item.mark.lab_report_id), :method => 'delete',  data: { confirm: 'Are you sure?' }, class: 'buttonRemoveMarkMainPage' %>
    <%end%>
  <%end%>
</div>
</body>
</html>

lab7/labs_control/app/views/lab_reports/new.html.erb
<h1 style="text-align:center;padding-top: 200px">Create labs report</h1>

<div style=" padding-left: 750px; padding-right: 200px;padding-bottom: 200px; ">
  <%= form_for :lab_report, url: lab_reports_path do |f| %>
    <% if @lab_report != nil%>
      <% if @lab_report.errors.any? %>
        <% @lab_report.errors.full_messages.each do |msg| %>
          <div class= "alertLabReport">
            <%= msg%>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <p >
      title <br>
      <%= f.text_field :title, :class => 'title'%>
    </p>

    <p >
      description<br>
      <%= f.text_area :description, :class => 'description' %>
    </p>

    <p >
      <%= f.submit "Save", :class => 'saveReportButton'%>
    </p>
  <%end%>
</div>

lab7/labs_control/app/views/lab_reports/show.html.erb
<div class="showBlock">
  <h1> 
    <%= @lab_report.title %> 
  </h1>

  <p> 
    <%= @lab_report.description %> 
  </p>

  <p>
    <%= link_to '/' do %>
    <%= button_tag('Main page', type: 'submit')%>
    <%end%>
  </p>

</div>

lab7/labs_control/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabsControl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab7/labs_control/app/views/marks/new.html.erb
<div style=" padding-left: 950px; padding-right: 200px;padding-bottom: 200px;padding-top: 400px; ">
  <%= form_for :mark, url: lab_report_marks_path do |f| %>
    <%if @mark != nil%>
    <% if @mark.errors.any? %>
      <% @mark.errors.full_messages.each do |msg| %>
        <div class= "alertMark ">
          <%= msg%>
        </div>
      <% end %>
    <% end %>
    <% end %>
    
    <p >
      mark <br>
      <%= f.text_field :points%>
    </p>

    <p >
      <%= f.submit "Save"%>
    </p>
  <% end %>
</div>